include:
  # Sweep
  - board: nice_nano_v2
    shield: cradio_left
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sweep_left_peripheral
  - board: nice_nano_v2
    shield: cradio_right
    snippet: zmk-usb-logging
    # cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sweep_right
  - board: nrf52840dongle_nrf52840
    shield: cradio_dongle
    # snippet: studio-rpc-usb-uart
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sweep_dongle

    # Reset shields
  - board: nrf52840dongle_nrf52840
    shield: settings_reset
    cmake-args: -DCONFIG_BUILD_OUTPUT_HEX=y -DCONFIG_BUILD_OUTPUT_UF2=n
  - board: nice_nano_v2
    shield: settings_reset
