#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

usage() {
  cat <<'EOF'
Usage: ./flash-local.sh [--reset] [--check] [keyboard]

Guided local flashing for a dongleless split ZMK keyboard.

  keyboard   Artifact prefix under build/local (default: sweep)
  --reset    Erase settings on both halves before normal firmware.
             Use for broken/stale Bluetooth or split bonds.
  --check    Check dependencies and artifacts without flashing.
  -h, --help Show this help.

Examples:
  ./flash-local.sh
  ./flash-local.sh --reset
  ./flash-local.sh urchin
EOF
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
KEYBOARD=sweep
FULL_RESET=0
CHECK_ONLY=0
KEYBOARD_SET=0

while (( $# )); do
  case "$1" in
    --reset) FULL_RESET=1 ;;
    --check) CHECK_ONLY=1 ;;
    -h|--help) usage; exit 0 ;;
    --*) printf 'Unknown option: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
    *)
      if (( KEYBOARD_SET )); then
        printf 'Only one keyboard name may be supplied.\n' >&2
        exit 2
      fi
      KEYBOARD="$1"
      KEYBOARD_SET=1
      ;;
  esac
  shift
done

if [[ ! "$KEYBOARD" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  printf 'Invalid keyboard name: %s\n' "$KEYBOARD" >&2
  exit 2
fi

BUILD_DIR="$SCRIPT_DIR/build/local"
RESET_FIRMWARE="$BUILD_DIR/settings_reset.uf2"
LEFT_FIRMWARE="$BUILD_DIR/${KEYBOARD}_left_central.uf2"
RIGHT_FIRMWARE="$BUILD_DIR/${KEYBOARD}_right.uf2"
SUDO_KEEPALIVE_PID=""
ACTIVE_MOUNT=""
LEFT_SERIAL=""
RIGHT_SERIAL=""
FOUND_DEVICE=""
FOUND_SERIAL=""

cleanup() {
  local status=$?
  set +e
  if [[ -n "$ACTIVE_MOUNT" ]]; then
    sudo -n umount -l "$ACTIVE_MOUNT" >/dev/null 2>&1 || true
    rmdir "$ACTIVE_MOUNT" >/dev/null 2>&1 || true
  fi
  if [[ -n "$SUDO_KEEPALIVE_PID" ]]; then
    kill "$SUDO_KEEPALIVE_PID" >/dev/null 2>&1 || true
    wait "$SUDO_KEEPALIVE_PID" >/dev/null 2>&1 || true
  fi
  exit "$status"
}
trap cleanup EXIT INT TERM

fail() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

check_dependencies() {
  local command_name
  local missing=()
  for command_name in sudo udevadm lsblk findmnt mount umount blockdev cp sync sed mktemp sleep uname rmdir; do
    command -v "$command_name" >/dev/null 2>&1 || missing+=("$command_name")
  done
  (( ${#missing[@]} == 0 )) || fail "Missing required commands: ${missing[*]}"
  [[ "$(uname -s)" == Linux ]] || fail "This flasher currently supports Linux only."
}

check_artifacts() {
  local missing=()
  [[ -s "$LEFT_FIRMWARE" ]] || missing+=("$LEFT_FIRMWARE")
  [[ -s "$RIGHT_FIRMWARE" ]] || missing+=("$RIGHT_FIRMWARE")
  if (( FULL_RESET )); then
    [[ -s "$RESET_FIRMWARE" ]] || missing+=("$RESET_FIRMWARE")
  fi
  if (( ${#missing[@]} )); then
    printf 'Missing firmware artifact(s):\n' >&2
    printf '  %s\n' "${missing[@]}" >&2
    printf '\nBuild them from this repository root:\n' >&2
    printf '  make build KEYBOARD=%q\n' "$KEYBOARD" >&2
    (( FULL_RESET )) && printf '  make build KEYBOARD=settings-reset\n' >&2
    exit 1
  fi
}

list_nicenano_bootloaders() {
  local sys_block name device properties model label serial
  for sys_block in /sys/class/block/sd*; do
    [[ -e "$sys_block" ]] || continue
    name="${sys_block##*/}"
    device="/dev/$name"
    [[ -b "$device" ]] || continue
    properties="$(udevadm info --query=property --name="$device" 2>/dev/null || true)"
    model="$(sed -n 's/^ID_MODEL=//p' <<<"$properties")"
    label="$(sed -n 's/^ID_FS_LABEL=//p' <<<"$properties")"
    serial="$(sed -n 's/^ID_SERIAL_SHORT=//p' <<<"$properties")"
    if [[ "$model" == nRF_UF2 && "$label" == NICENANO && -n "$serial" ]]; then
      printf '%s|%s\n' "$device" "$serial"
    fi
  done
}

wait_for_bootloader() {
  local expected_serial="${1:-}" forbidden_serial="${2:-}"
  local deadline=$((SECONDS + 180)) line device serial
  local -a candidates=()

  FOUND_DEVICE=""
  FOUND_SERIAL=""
  while (( SECONDS < deadline )); do
    candidates=()
    while IFS='|' read -r device serial; do
      [[ -n "$device" && -n "$serial" ]] || continue
      if [[ -n "$expected_serial" && "$serial" != "$expected_serial" ]]; then
        continue
      fi
      if [[ -n "$forbidden_serial" && "$serial" == "$forbidden_serial" ]]; then
        continue
      fi
      candidates+=("$device|$serial")
    done < <(list_nicenano_bootloaders)

    if (( ${#candidates[@]} == 1 )); then
      line="${candidates[0]}"
      FOUND_DEVICE="${line%%|*}"
      FOUND_SERIAL="${line#*|}"
      printf '\r  %s✓ found%s %s (serial %s)                    \n' \
        "$GREEN" "$RESET" "$FOUND_DEVICE" "$FOUND_SERIAL"
      return 0
    fi
    if (( ${#candidates[@]} > 1 )); then
      printf '\n' >&2
      fail "More than one matching NICENANO bootloader is connected. Unplug all but the requested half."
    fi
    printf '\r  waiting for NICENANO bootloader… %3ss ' "$((deadline - SECONDS))"
    sleep 1
  done
  printf '\n' >&2
  fail "Timed out waiting for the NICENANO bootloader. Double-tap reset and check the USB data cable."
}

verify_bootloader() {
  local device="$1" expected_serial="$2" properties model label serial
  [[ -b "$device" ]] || fail "$device disappeared before flashing."
  properties="$(udevadm info --query=property --name="$device")"
  model="$(sed -n 's/^ID_MODEL=//p' <<<"$properties")"
  label="$(sed -n 's/^ID_FS_LABEL=//p' <<<"$properties")"
  serial="$(sed -n 's/^ID_SERIAL_SHORT=//p' <<<"$properties")"
  [[ "$model" == nRF_UF2 && "$label" == NICENANO && "$serial" == "$expected_serial" ]] || \
    fail "Device identity changed; refusing to flash $device."
}

wait_for_usb_product() {
  local serial="$1" expected_product="${2:-}"
  local deadline=$((SECONDS + 30)) usb_node actual_serial product
  while (( SECONDS < deadline )); do
    for usb_node in /sys/bus/usb/devices/*; do
      [[ -r "$usb_node/serial" && -r "$usb_node/product" ]] || continue
      actual_serial="$(<"$usb_node/serial")"
      [[ "$actual_serial" == "$serial" ]] || continue
      product="$(<"$usb_node/product")"
      if [[ -z "$expected_product" && "$product" != "nice!nano" ]]; then
        printf '  %s✓ rebooted as%s %s\n' "$GREEN" "$RESET" "$product"
        return 0
      fi
      if [[ -n "$expected_product" && "$product" == "$expected_product" ]]; then
        printf '  %s✓ rebooted as%s %s\n' "$GREEN" "$RESET" "$product"
        return 0
      fi
    done
    sleep 1
  done
  if [[ -n "$expected_product" ]]; then
    fail "Firmware copy finished, but serial $serial did not reboot as '$expected_product'."
  fi
  fail "Firmware copy finished, but serial $serial did not reboot into application firmware."
}

flash_uf2() {
  local firmware="$1" serial="$2" destination_name="$3" expected_product="$4"
  local device mount_options mount_target

  wait_for_bootloader "$serial"
  device="$FOUND_DEVICE"
  verify_bootloader "$device" "$serial"

  while IFS= read -r mount_target; do
    [[ -n "$mount_target" ]] || continue
    sudo umount "$mount_target"
  done < <(findmnt -rn -S "$device" -o TARGET || true)

  ACTIVE_MOUNT="$(mktemp -d /tmp/zmk-flash.XXXXXX)"
  sudo blockdev --setrw "$device"
  sudo mount -t vfat -o rw,flush "$device" "$ACTIVE_MOUNT"
  mount_options="$(findmnt -rn -S "$device" -o OPTIONS)"
  [[ ",$mount_options," == *,rw,* ]] || fail "$device remained read-only after the forced mount."

  printf '  flashing %s…\n' "${firmware##*/}"
  sudo cp -- "$firmware" "$ACTIVE_MOUNT/$destination_name"
  sudo sync -f "$ACTIVE_MOUNT" 2>/dev/null || true

  sudo umount -l "$ACTIVE_MOUNT" 2>/dev/null || true
  rmdir "$ACTIVE_MOUNT" 2>/dev/null || true
  ACTIVE_MOUNT=""
  wait_for_usb_product "$serial" "$expected_product"
}

start_sudo_keepalive() {
  say "Administrator access is needed only for the removable UF2 block device."
  sudo -v
  (
    while sleep 45; do
      sudo -n -v >/dev/null 2>&1 || exit
    done
  ) &
  SUDO_KEEPALIVE_PID=$!
}

check_dependencies
check_artifacts

if (( CHECK_ONLY )); then
  printf 'Ready: dependencies and firmware artifacts are present.\n'
  printf '  %s\n  %s\n' "$LEFT_FIRMWARE" "$RIGHT_FIRMWARE"
  (( FULL_RESET )) && printf '  %s\n' "$RESET_FIRMWARE"
  exit 0
fi

if (( FULL_RESET )); then
  TOTAL_STAGES=5
else
  TOTAL_STAGES=3
fi

banner "Guided ${KEYBOARD} firmware flash"

stage "Preflight"
say "Firmware is resolved relative to this script, not the current directory:"
note "left:  $LEFT_FIRMWARE"
note "right: $RIGHT_FIRMWARE"
(( FULL_RESET )) && note "reset: $RESET_FIRMWARE"
step "Unplug both keyboard halves from USB. Keep their battery switches on."
pause "Press Enter when no NICENANO bootloader volume is connected."
if (( FULL_RESET )); then
  warn "Recovery mode erases Bluetooth and split bonds on both halves."
  confirm "Continue with the full settings reset?" || fail "Cancelled before changing either half."
fi
start_sudo_keepalive

if (( FULL_RESET )); then
  stage "Reset left half"
  step "Connect the LEFT half with a USB data cable."
  step "Double-tap its physical reset button to enter the NICENANO bootloader."
  pause "Press Enter after double-tapping reset."
  wait_for_bootloader
  LEFT_SERIAL="$FOUND_SERIAL"
  flash_uf2 "$RESET_FIRMWARE" "$LEFT_SERIAL" settings_reset.uf2 "SETTINGS RESET"

  stage "Flash left central"
  step "Leave the LEFT half connected and double-tap reset again."
  pause "Press Enter when its NICENANO bootloader reappears."
  flash_uf2 "$LEFT_FIRMWARE" "$LEFT_SERIAL" "${KEYBOARD}_left_central.uf2" ""

  stage "Reset right half"
  step "Unplug the LEFT half, connect the RIGHT half, and double-tap its reset button."
  pause "Press Enter when the right NICENANO bootloader appears."
  wait_for_bootloader "" "$LEFT_SERIAL"
  RIGHT_SERIAL="$FOUND_SERIAL"
  flash_uf2 "$RESET_FIRMWARE" "$RIGHT_SERIAL" settings_reset.uf2 "SETTINGS RESET"

  stage "Flash right peripheral"
  step "Leave the RIGHT half connected and double-tap reset again."
  pause "Press Enter when its NICENANO bootloader reappears."
  flash_uf2 "$RIGHT_FIRMWARE" "$RIGHT_SERIAL" "${KEYBOARD}_right.uf2" ""
else
  stage "Flash left central"
  step "Connect the LEFT half with a USB data cable."
  step "Double-tap its physical reset button to enter the NICENANO bootloader."
  pause "Press Enter after double-tapping reset."
  wait_for_bootloader
  LEFT_SERIAL="$FOUND_SERIAL"
  flash_uf2 "$LEFT_FIRMWARE" "$LEFT_SERIAL" "${KEYBOARD}_left_central.uf2" ""

  stage "Flash right peripheral"
  step "Unplug the LEFT half, connect the RIGHT half, and double-tap its reset button."
  pause "Press Enter when the right NICENANO bootloader appears."
  wait_for_bootloader "" "$LEFT_SERIAL"
  RIGHT_SERIAL="$FOUND_SERIAL"
  flash_uf2 "$RIGHT_FIRMWARE" "$RIGHT_SERIAL" "${KEYBOARD}_right.uf2" ""
fi

finish
say "Both halves now run the local $KEYBOARD build."
if (( FULL_RESET )); then
  step "Unplug USB and power-cycle both halves so they create a fresh split bond."
  step "Reconnect the left half, then remove and pair 'Sweep' again in your OS Bluetooth settings."
else
  step "Reconnect or power-cycle the halves if they do not rejoin immediately."
fi
